import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MarkdownProvider } from "@/components/context/MarkdownContext";
import { HeadingProvider } from "@/components/context/HeadingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<HeadingProvider>
			<MarkdownProvider>{children}</MarkdownProvider>
		</HeadingProvider>
	);
}
